name = "cdnsd/onchain"
version = "0.0.0"
compiler = "v1.1.19"
plutus = "v3"
license = "MIT"
description = "Aiken contracts for project 'cdnsd/onchain'"

[repository]
user = "cdnsd"
project = "onchain"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[config]
